In [6]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('coldata_nsqip.csv', index_col=0)
data.head()

,SEX,RACE_NEW,PRNCPTX,AGE,ELECTSURG,EMERGNCY,WNDCLAS,ASACLAS,DIABETES,SMOKE,...,genotypePC1,genotypePC2,genotypePC3,genotypePC4,race,mrn,montreal,date collected,IASC,SSI
sample,,,,,,,,,,,,,,,,,,,,,
PB630,Male,Some Other Race,"Colectomy, partial; with anastomosis",73.68,NaN,NaN,NaN,ASA 3 - Severe Disturb,No,Yes,...,NaN,NaN,NaN,NaN,non-hispanic black,40062903,NaN,2021-01-25,No,No
PB447,Male,White,"Laparoscopy, surgical; colectomy, total, abdom...",54.12,Yes,No,Clean/Contaminated,ASA 3 - Severe Disturb,Non-Insulin,No,...,NaN,NaN,NaN,NaN,non-hispanic white,100055287526,NaN,2018-08-29,No,No
PB495,Female,White,"Laparoscopy, surgical; colectomy, total, abdom...",54.79,Yes,No,Contaminated,ASA 3 - Severe Disturb,No,No,...,NaN,NaN,NaN,NaN,non-hispanic white,100034239242,NaN,2018-12-03,No,No
PB53,Male,White,"Colectomy, total, abdominal, with proctectomy;...",45.29,Yes,No,Clean/Contaminated,ASA 3 - Severe Disturb,No,No,...,NaN,NaN,NaN,NaN,non-hispanic white,12364659,E3 (HH),2013-09-09,Yes,Yes
PB269,Male,White,"Laparoscopy, surgical; colectomy, total, abdom...",33.23,Yes,No,Clean/Contaminated,ASA 2 - Mild Disturb,No,No,...,-0.028342,-0.021577,-0.004032,0.002902,non-hispanic white,100048477473,NaN,2017-03-22,No,No

In [5]:
pd.crosstab(data['IASC'], data['SSI'], margins=True)

SSI   No  Yes  All
IASC
No    90    9   99
Yes    0   11   11
All   90   20  110

In [8]:
data['SSI_IASC'] = np.NaN
data.loc[data['SSI'] == 'No', 'SSI_IASC'] = 'No infection'
data.loc[data['SSI'] == 'Yes', 'SSI_IASC'] = 'SSI'
data.loc[data['IASC'] == 'Yes', 'SSI_IASC'] = 'IASC'
data['SSI_IASC'].value_counts(dropna=False)

SSI_IASC
No infection    90
IASC            11
SSI              9
Name: count, dtype: int64

In [9]:
data.to_csv('coldata_nsqip.csv')